### ISSUE TITLE
Multiple slider instances break

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_viz#167]
It is possible to show multiple slider instances but only one will allow you to control the model.

**Comment by tbekolay** [comment]
Consensus: we should remove the old slider when making a new one (client-side).

**Comment by s72sue** [comment]
Fix in #286

**Comment by tbekolay** [comment]
#286 merged in now, so this is done! Slight but that is reported in #291, but that's definitely not a blocking issue for the release.
