### ISSUE TITLE
Shut down the server when the last browser window closes

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_viz#205]
We should be able to detect when there are no browser windows open, and shut down the server at that point (with perhaps a few seconds of grace time).

**Comment by tbekolay** [comment]
This would be cool for sure for most use cases! I think should also be configurable though (probably a command-line option for it to stay alive, or an RC file thing). Especially for something like doing a live presentation, you might be relying on the server staying alive when opening and closing browser tabs live.

**Comment by tcstewar** [comment]
+1 for configurable option.  The default would be to automatically close, though, I think (this might also be a good thing to add for the global .config file and menu)

**Comment by tbekolay** [comment]
+1 auto-close by default!
