### ISSUE TITLE
Middle click reset to 0 does not update the graph.

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo_viz#210]
![image](https://cloud.githubusercontent.com/assets/10402911/7864525/a3a0e47e-0530-11e5-9155-93cb6de18f96.png)

**Comment by tcstewar** [comment]
I can't replicate this.  What browser?  What model?  Does it happen all the time for you or just sometimes?

**Comment by cchan987** [comment]
> I can't replicate this. What browser? What model? Does it happen all the time for you or just sometimes?

I found the issue with this was actually the middle click was broken and did not update the graphs.

**Comment by tbekolay** [comment]
No middle clicks; keeping this open to make sure that the middle click code is cleaned up.
