### ISSUE TITLE
Slider value can be lowered past range bounds

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo_viz#213]
Hard to describe:
If you move the slider to the bottom so it is at -1.00
then while still holding the click down, move the mouse further down, out of the slider, it will lower the value even more (lower than -1.00), while still displaying -1.

![image](https://cloud.githubusercontent.com/assets/10402911/7865799/411ac564-0539-11e5-8d4d-772a81873383.png)

**Comment by tbekolay** [comment]
Sounds like a problem with the y-axis domain or range.

**Comment by cchan987** [comment]
Previously the slider was detecting when it hit the bottom and then would stop sending updates about mouse movement until the mouse was back in the slider range

**Comment by tbekolay** [comment]
Oh gotcha, I misunderstood the description; I retract my comment!

**Comment by tcstewar** [comment]
The problem is here:

```python
VIZ.SliderControl.prototype.display_value = function(value) {
    if (value < this.min) {
        value = this.min;
    }
    if (value > this.max) {
        value = this.max;
    }

    this.value = value;

    this.update_handle_pos(value);
    this.update_value_text(value);
}

VIZ.SliderControl.prototype.set_value = function(value) {
    if (this.value != value) {
        this.display_value(value);
        this.dispatch('change', {'target': this, 'value': value});
    }
};
```

When ```set_value``` is called, it's dispatching the change but not chekcing the limits.

I'm not sure if the right solution is to check the limits in both ```set_value``` and ```display_value``, or just in ```set_value```.

**Comment by jgosmann** [comment]
I think, the `this.value` should be dispatched because that's the actual value the slider is set to.

**Comment by tcstewar** [comment]
> I think, the this.value should be dispatched because that's the actual value the slider is set to.

Oo, that's kinda cute.  I like that.
