### ISSUE TITLE
Netgraph takes super long in Firefox to load

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_viz#222]
no idea why ...

**Comment by tcstewar** [comment]
I see this every now and then, and then it magically goes away.  Do you have a situation where it's reliably reproducible?

**Comment by jgosmann** [comment]
When I created the issue it was ... now it isn't. :/

**Comment by tcstewar** [comment]
> When I created the issue it was ... now it isn't. :/

:(  I have no idea what causes this....

**Comment by jgosmann** [comment]
[This might be the problem.](https://bugzilla.mozilla.org/show_bug.cgi?id=782704)

**Comment by jgosmann** [comment]
[or this?](https://bugzilla.mozilla.org/show_bug.cgi?id=711793)

**Comment by jgosmann** [comment]
This is still not completely solved: When we shutdown the server, all sockets are just closed without doing a proper closing handshake on the websockets.

**Comment by hunse** [comment]
Do we need a handshake [here](https://github.com/nengo/nengo_viz/blob/c6b3f8997ed0d51e9de67c7e7fdac8f11ad1a7d9/nengo_viz/swi.py#L549) too?

**Comment by jgosmann** [comment]
No, there the socket is already closed. That's the reason we get he exception. If the server dies because of an exception we could still try to close everything properly. but I'm not that concerned about it because something already went wrong, so the connections might as well terminate abnormally too.
