### ISSUE TITLE
Reset shuts down the server ...

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_viz#241]
... because the page is reloaded and thus all open connections are closed.

**Comment by tcstewar** [comment]
Weird... this doesn't happen for me in Windows under Chrome or Firefox

**Comment by jgosmann** [comment]
It's pretty consistent and pretty annoying ... (though I can work around it by keeping open a second tab).
Not sure what the best fix is:
1. Do not reload the whole page on reset?
2. Disable the auto-shutdown during reload?
3. Have a time delay before the shutdown?

Option 1 and 2 won't fix that the server shuts down when hitting the browser's reload button. So option 3 is probably the best.

**Comment by tcstewar** [comment]
The time delay seems like the right approach to me.

What operating system and browser are you on?  Is anyone else seeing this happen?

**Comment by jgosmann** [comment]
OS X + Firefox
