### ISSUE TITLE
Scrolling is backwards?

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo_viz#258]
I just checked out master and was surprised that the scrollwheel behavior is the opposite of what I would have expected. Scrolling up zooms out, while scrolling down zooms in. I know that this behavior makes more sense with trackpads in Mac OS X, but it's the opposite of what linux / windows people expect. Could this be specific to the platform?

**Comment by tcstewar** [comment]
It's also opposite for me (on scrollwheel, but not on trackpad).  So on the trackpad, doing a two-finger slide upwards zooms in, but with the mouse scrollwheel, going upward zooms out.  This is on Windows in Firefox and Chrome.

**Comment by tbekolay** [comment]
Consensus: Make it the same as Google Maps.
