### ISSUE TITLE
Set focus to the text-field when a modal pops up for user input

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo_viz#262]
When a modal pops up for something like setting the range on a plot, it would be nice if the user can start typing right away, without having to click on the text box first.

It would also be nice if pressing enter would accept the form. Currently on chrome pressing enter will close the dialog as if the cancel button was pushed.

**Comment by celiasmith** [comment]
The first is already in #195 I'm adding the 2nd suggestion now :smiley: 
(modals will be ready for scrutiny once that's merged).

Brent Komer wrote:

**Comment by jgosmann** [comment]
This has been addressed in #195.
