### ISSUE TITLE
Swap to sharp cornered networks

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo_viz#268]
See if we like it Thursday evening.

**Comment by tcstewar** [comment]
Okay, it's in master now.  Let's see how we feel in a few days!  :)

**Comment by tbekolay** [comment]
This is the last unsolved issue, other than the code editor and the release! Anyone have any strong opinions on this?

**Comment by jgosmann** [comment]
Haven't seen the swapped style that much because I mostly worked on branches that haven't been rebased until today. But so far the change didn't stand out very much to me which is a good thing, I guess.

**Comment by tbekolay** [comment]
Consensus seems to be either "cool" or "either way" so let's keep it like this!
