### ISSUE TITLE
Possible to have two sliders with undo/redo

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo_viz#291]
If you add a slider, then readd it, it will get replaced. If you undo these steps for a while, then redo, you can end up with two sliders.

First step is to figure out a better reproducible set of steps for this :)

**Comment by bjkomer** [comment]
Found a reproducible set of steps:
- Create slider
- Reposition slider
- Create another slider
- Press undo 3 times
- Press redo 3 times

Another bug I noticed is when you undo the creation of the second slider, the first slider doesn't show up again, when it really should. I think these two bugs are related.

**Comment by s72sue** [comment]
thanks Brent, this works very well !
