### ISSUE TITLE
Is it possible to git rid of the IPython warning?

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_viz#297]
Even when I'm not running in IPython, I get this on startup:

```
:0: FutureWarning: IPython widgets are experimental and may change in the future.
```

Is there any way to not have that happen?

**Comment by tbekolay** [comment]
This is raised by IPython 3+ because when you `import nengo`, we add some stuff (like the progress bar) to IPython. This will be fixed in Nengo 2.1.

**Comment by tcstewar** [comment]
Ah, right...  never mind.  Thanks!  :)

**Comment by jgosmann** [comment]
Actually, I believe that warning will still be there ...

**Comment by tbekolay** [comment]
But only when you load the extension right?

**Comment by jgosmann** [comment]
I guess we could move the IPython progress bar into that module to achieve this?

**Comment by jgosmann** [comment]
I added a commit to nengo/nengo#693 to achieve this.
