### ISSUE TITLE
ipynb integration breaks server reloading

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_viz#299]
Something in the IPython system means that the server shuts down immediately on a page reload or a browser window close (even if there are other browser windows open).

To replicate:
- start nengo_viz
- hit reload

or 
- start nengo_viz
- open a second tab to it
- close one of the tabs

**Comment by tcstewar** [comment]
(note: this didn't happen before the IPython stuff got merged)

**Comment by tcstewar** [comment]
@jgosmann I think the problem is here:

https://github.com/nengo/nengo_viz/blob/master/nengo_viz/server.py#L154

shouldn't it be:
```python
if isinstance(component, nengo_viz.components.SimControl):
    if self.server.viz.interactive:
        if self.server.viz.count_sims() == 0:
            print(
                "No connections remaining to the nengo_viz "
                "server.")
            self.server.shutdown()
    else:
        self.server.shutdown()
```

**Comment by jgosmann** [comment]
I think, it should be as in #303.
