### ISSUE TITLE
Spacebar does not properly start/stop the simulation if focus is on the play button in Firefox

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo_viz#302]
Firefox strikes again! If you click play with your mouse to start the simulation, the spacebar hotkey will not work properly. It will stop the simulation when you press it, but then start it again immediately when you release it. I think this is because when you have focus on the button, enter and spacebar will act like you clicked on it, essentially sending play/pause commands in pairs of two. This issue doesn't happen on Chrome of course.

**Comment by jgosmann** [comment]
Works in my Firefox. What's your version?

**Comment by jgosmann** [comment]
ok, can reproduce on Linux ...
